### ISSUE TITLE
`.buildozerrc` config search

### ISSUE THREAD

**Issue by MartijnCuppens** [Intracto/buildozer#43]
It would be nice if buildozer searched for `.buildozerrc` files all over a project. This will make it easier to develop per component.

I'll illustrate this idea with a Drupal setup. We can have a folder structure like:
```
project/
├── modules/
│   ├── contrib
│   │   └── …
│   └── custom
│       └── my_module
│           ├── scss
│           ├── js
│           ├── .buildozerrc
│           └── …
├── themes/
│   ├── contrib
│   │   └── …
│   └── custom
│       └── my_theme
│           ├── scss
│           ├── js
│           ├── .buildozerrc
│           └── …
└── .buildozerrc
```

The `.buildozerrc` files in the theme & module folders can be empty if we use the default folder structure.

In the main `.buildozerrc` we can define something like:
```
config_search:
  enabled: true # disabled by default?
  excluded_paths: # maybe we can just define a glob?
    - vendor
    - node_modules
    - modules/contrib 
    - themes/contrib
# There won't be any assets in the root, so we can remove these with:
scss: []
js: []
js-concat: []
svg-sprite: []
```
